# Generated by Django 5.0.3 on 2024-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='cliente',
            new_name='cedulaCliente',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='cedula',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
    ]
