# Generated by Django 5.0.3 on 2024-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cliente_correoelectronico_alter_servicio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cedulaCliente',
            field=models.CharField(max_length=20),
        ),
    ]
