# Generated by Django 5.0.3 on 2024-06-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_servicio_cedulacliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='cedulaCliente',
        ),
        migrations.AddField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='api.cliente'),
        ),
    ]
