# Generated by Django 5.0.3 on 2024-06-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_servicio_cedulacliente_servicio_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='api.cliente'),
        ),
    ]
