# Generated by Django 5.0.3 on 2024-06-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_servicio_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='cliente',
        ),
    ]
