# Generated by Django 5.0.3 on 2024-06-20 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_servicio_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='cedulaCliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
    ]
