# Generated by Django 5.0.3 on 2024-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=50)),
                ('estudiante', models.CharField(max_length=50)),
                ('salon', models.CharField(max_length=2)),
                ('local', models.CharField(max_length=10)),
            ],
        ),
    ]
